Atividade1/Models/Convidado.cs
namespace Atividade1.Models
{
    public class Convidado
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string EMail { get; set; }
        public string Telefone { get; set; }
        public bool comparecimento { get; set; }
        public string comparecimentoString { get => comparecimento ? "Sim" : "Não"; }
    }
}

Atividade1/Models/ErrorViewModel.cs
namespace Atividade1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Atividade1/Controllers/ConvidadoController.cs
using Atividade1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Atividade1.Controllers
{
    public class ConvidadoController : Controller
    {
        public static IList<Convidado> convidados = new List<Convidado>()
        {
            new Convidado() { Id = 1,Nome="João Lucas Lourenço", Telefone="35997275693",EMail="jao.lucas@gmail.com",comparecimento=false}
        };


        public IActionResult Index()
        {
            return View(convidados);
        }


        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Convidado convidado)
        {
            convidado.Id = convidados.Select(conv => conv.Id).Max() + 1;
            convidados.Add(convidado);
            return RedirectToAction("Index");
        }


        public IActionResult Details(long id)
        {
            return View(convidados.Where(conv => conv.Id == id).First());
        }


        public IActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Convidado convidado)
        {
            convidados.Remove(convidados.Where(conv => conv.Id == convidado.Id).First());
            convidados.Add(convidado);
            return RedirectToAction("Index");
        }

        

        public IActionResult Delete(int id)
        {
            return View(convidados.Where(conv => conv.Id == id).First());
        }
        [HttpPost]
        public IActionResult Delete(Convidado convidado)
        {
            convidados.Remove(convidados.Where(conv => conv.Id == convidado.Id).First());
            return RedirectToAction("Index");
        }



        public IActionResult SortByConfirmation()
        {
            return View(convidados.Where(conv => conv.comparecimento == true));
        }

        public IActionResult SortByNotConfirmation()
        {
            return View(convidados.Where(conv => conv.comparecimento == false));
        }
    }
}

Atividade1/Controllers/HomeController.cs
using Atividade1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Atividade1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Atividade1/Views/Convidado/Create.cshtml
@model Atividade1.Models.Convidado

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Convidado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EMail" class="control-label"></label>
                <input asp-for="EMail" class="form-control" />
                <span asp-validation-for="EMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="comparecimento" /> @Html.DisplayNameFor(model => model.comparecimento)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Atividade1/Views/Convidado/Delete.cshtml
@model Atividade1.Models.Convidado

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h4>Tem certeza que deseja excluir este Convidado?</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Delete">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" readonly />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EMail" class="control-label"></label>
                <input asp-for="EMail" class="form-control" readonly />
                <span asp-validation-for="EMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" readonly />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Atividade1/Views/Convidado/Details.cshtml
@model Atividade1.Models.Convidado

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Convidado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EMail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EMail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.comparecimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.comparecimento)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

Atividade1/Views/Convidado/Edit.cshtml
@model Atividade1.Models.Convidado

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Convidado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EMail" class="control-label"></label>
                <input asp-for="EMail" class="form-control" />
                <span asp-validation-for="EMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="comparecimento" /> @Html.DisplayNameFor(model => model.comparecimento)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Atividade1/Views/Convidado/Index.cshtml
@model IEnumerable<Atividade1.Models.Convidado>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Adicionar novo convidado</a>
</p>

<p>
    <a asp-action="SortByConfirmation">Listar apenas quem confirmou presença</a>
</p>
<p>
    <a asp-action="SortByNotConfirmation">Listar apenas quem não confirmou presença</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EMail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.comparecimento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EMail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.comparecimentoString)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id}) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Atividade1/Views/Convidado/SortByConfirmation.cshtml
@model IEnumerable<Atividade1.Models.Convidado>

@{
    ViewData["Title"] = "SortByConfirmation";
}

<h1>SortByConfirmation</h1>

<<p>
    <a asp-action="Create">Adicionar novo convidado</a>
</p>


<p>
    <a asp-action="SortByNotConfirmation">Listar apenas quem não confirmou presença</a>
</p>

<p>
    <a asp-action="Index">Listar todos os convidados</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Nome
            </th>
            <th>
                Email
            </th>
            <th>
                Telefone
            </th>
            <th>
                Comparecimento
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                    @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.EMail)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.comparecimentoString)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
    </tbody>
</table>

Atividade1/Views/Convidado/SortByNotConfirmation.cshtml
@model IEnumerable<Atividade1.Models.Convidado>

@{
    ViewData["Title"] = "SortByNotConfirmation";
}

<h1>SortByNotConfirmation</h1>

<p>
    <a asp-action="Create">Adicionar novo convidado</a>
</p>

<p>
    <a asp-action="SortByConfirmation">Listar apenas quem confirmou presença</a>
</p>
<p>
    <a asp-action="Index">Listar todos os convidados</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EMail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.comparecimento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EMail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.comparecimentoString)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Atividade1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Atividade1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Atividade1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Atividade1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Convidado" asp-action="Index">Convidados</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>